const { app, BrowserWindow } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../.test-output/dashboard');
app.setPath('userData', path.join(output, 'profile'));
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => {
  let win;
  try {
    await fs.mkdir(output, { recursive: true });
    win = new BrowserWindow({ width: 1440, height: 1000, show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
    const errors = [];
    win.webContents.on('console-message', event => { if (event.level === 'error') { errors.push(event.message); console.error(event.message); } });
    const js = async code => { try { return await win.webContents.executeJavaScript(code, true); } catch (error) { console.error('SCRIPT', code); throw error; } };
    const button = label => js(`document.querySelector('button[aria-label=${JSON.stringify(label)}]').click()`);
    const setInput = (selector, value) => js(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    await win.loadFile(path.resolve(__dirname, '../dist/index.html')); await delay(1100);
    await js('localStorage.clear()'); win.webContents.reload(); await delay(1100);
    win.show(); win.focus(); await delay(200);
    await button('サイドバーを切り替え'); await delay(150);
    assert.ok(await js(`document.querySelector('.main').getBoundingClientRect().width >= innerWidth - 1`));
    assert.equal(await js(`document.querySelector('.main').getBoundingClientRect().left`), 0);
    assert.ok(await js(`document.querySelector('.tiptap').getBoundingClientRect().width > 600`));
    await fs.writeFile(path.join(output, 'sidebar-closed.png'), (await win.webContents.capturePage()).toPNG());
    await button('サイドバーを切り替え'); await delay(100);
    assert.ok(await js(`document.querySelector('.main').getBoundingClientRect().left >= 200`));
    await button('ダッシュボードへ'); await delay(350);
    assert.equal(await js(`document.querySelectorAll('.scenario-card').length`), 1);
    await js(`(()=>{const key='trpg-canvas-documents-v1';const data=JSON.parse(localStorage.getItem(key));const original=Object.values(data)[0];const id=crypto.randomUUID();data[id]={doc:{...original.doc,id,title:'星空の観測所',subtitle:'星をめぐる探索シナリオ'},revision:crypto.randomUUID()};localStorage.setItem(key,JSON.stringify(data));})()`);
    await button('ダッシュボードの一覧を更新'); await delay(250);
    assert.equal(await js(`document.querySelectorAll('.scenario-card').length`), 2);
    await setInput('[aria-label="ダッシュボードのシナリオ検索"]', '星空'); await delay(100);
    assert.equal(await js(`document.querySelectorAll('.scenario-card').length`), 1);
    await setInput('[aria-label="ダッシュボードのシナリオ検索"]', '');
    await fs.writeFile(path.join(output, 'dashboard.png'), (await win.webContents.capturePage()).toPNG());
    await js(`document.querySelector('.dashboard-actions .primary-button').click()`); await delay(400);
    await setInput('[aria-label="シナリオタイトル"]', 'GMメモ検証');
    await button('GMメモ（角丸・網掛け）'); await delay(150);
    assert.ok(await js(`!!document.querySelector('.tiptap aside[data-gm-note]')`));
    assert.equal(await js(`document.querySelectorAll('.tiptap > h2').length`), 3);
    assert.equal(await js(`document.querySelector('.tiptap > h2').textContent`), '導入');
    assert.equal(await js(`document.querySelectorAll('.gm-note blockquote, .gm-note h2').length`), 0);
    await js(`document.execCommand('insertText',false,'GMだけの秘密の手がかり。')`); await delay(150);
    assert.ok(await js(`document.querySelector('.gm-note').innerText.includes('GMだけの秘密の手がかり。')`));
    assert.equal(await js(`getComputedStyle(document.querySelector('.gm-note')).borderTopLeftRadius`), '13px');
    assert.ok(await js(`getComputedStyle(document.querySelector('.gm-note')).backgroundImage.includes('repeating-linear-gradient')`));
    win.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Enter', modifiers: ['control'] });
    win.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Enter', modifiers: ['control'] });
    await delay(150);
    assert.equal(await js(`getSelection().anchorNode.parentElement.closest('.gm-note')`), null);
    await js(`document.execCommand('insertText',false,'メモの外の本文です。')`); await delay(200);
    // Navigation must flush a pending autosave before showing the card.
    await button('ダッシュボードへ'); await delay(350);
    assert.ok(await js(`Array.from(document.querySelectorAll('.scenario-card')).some(el=>el.textContent.includes('GMメモ検証'))`));
    const doc = await js(`Object.values(JSON.parse(localStorage.getItem('trpg-canvas-documents-v1'))).find(item=>item.doc.title==='GMメモ検証').doc`);
    assert.ok(doc.markdown.includes('> [!GM]'));
    assert.ok(doc.content.content.some(node => node.type === 'gmNote'));
    await js(`Array.from(document.querySelectorAll('.scenario-card')).find(el=>el.textContent.includes('GMメモ検証')).click()`); await delay(350);
    assert.ok(await js(`document.querySelector('.gm-note').innerText.includes('GMだけの秘密')`));
    await fs.writeFile(path.join(output, 'gm-note.png'), (await win.webContents.capturePage()).toPNG());
    await win.setSize(1000, 800); await button('サイドバーを切り替え'); await delay(200);
    assert.ok(await js(`document.querySelector('.main').getBoundingClientRect().width >= innerWidth - 1`));
    assert.ok(await js(`document.documentElement.scrollWidth <= innerWidth`));
    await js(`(()=>{const data=new DataTransfer();data.items.add(new File([${JSON.stringify(doc.markdown)}],'gm-roundtrip.md',{type:'text/markdown'}));const input=document.querySelector('input[type="file"]');input.files=data.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`); await delay(450);
    assert.ok(await js(`document.querySelector('.gm-note').innerText.includes('GMだけの秘密')`));
    assert.equal(await js(`document.querySelectorAll('.tiptap > h2').length`), 3);
    await js(`(()=>{const el=document.querySelector('.gm-note p');const range=document.createRange();range.selectNodeContents(el);range.collapse(false);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.querySelector('.tiptap').focus();})()`);
    await button('GMメモ（角丸・網掛け）'); await delay(100);
    assert.equal(await js(`document.querySelectorAll('.gm-note').length`), 0);
    assert.ok(await js(`document.querySelector('.tiptap').textContent.includes('GMだけの秘密')`));
    await button('元に戻す（Ctrl+Z）'); await delay(150);
    assert.equal(await js(`document.querySelectorAll('.gm-note').length`), 1);
    await delay(850);
    const { exportHtml } = await import('../src/export.mjs');
    const htmlPath = path.join(output, 'gm-note.html');
    await fs.writeFile(htmlPath, exportHtml(doc)); await win.loadFile(htmlPath); await delay(200);
    assert.ok(await js(`document.querySelector('.gm-note').innerText.includes('GMだけの秘密')`));
    assert.equal(await js(`getComputedStyle(document.querySelector('.gm-note')).borderTopLeftRadius`), '12px');
    await fs.writeFile(path.join(output, 'gm-note.pdf'), await win.webContents.printToPDF({ printBackground: true, pageSize: 'A4', margins: { top: .5, bottom: .5, left: .5, right: .5 } }));
    assert.deepEqual(errors, []);
    console.log('PASS: sidebar collapse/expand at two sizes, dashboard navigation/refresh/search/new/open, save-before-navigation, GM note insertion/edit/exit/persistence, HTML and PDF');
    win.destroy(); app.exit(0);
  } catch (error) { console.error(error); win?.destroy(); app.exit(1); }
});
