const { app, BrowserWindow } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../.test-output/hierarchy');
app.setPath('userData', path.join(output, 'profile'));
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => {
  let win;
  try {
    await fs.mkdir(output, { recursive: true });
    win = new BrowserWindow({ width: 1440, height: 1000, show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } });
    const errors = [];
    win.webContents.on('console-message', event => { if (event.level === 'error') { errors.push(event.message); console.error(event.message); } });
    const js = code => win.webContents.executeJavaScript(code, true);
    const click = text => js(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()===${JSON.stringify(text)})?.click()`);
    const flowTab = () => js(`Array.from(document.querySelectorAll('.view-tabs button')).find(b=>b.textContent.includes('フローチャート')).click()`);
    await win.loadFile(path.resolve(__dirname, '../dist/index.html')); await delay(1000);
    await js('localStorage.clear()'); win.webContents.reload(); await delay(1100);
    win.show(); win.focus(); await delay(200);
    await js(`(()=>{const key='trpg-canvas-documents-v1',all=JSON.parse(localStorage.getItem(key));Object.values(all).forEach(v=>{v.doc.markdown=v.doc.markdown.replace(/^##/gm,'#');v.doc.content.content.forEach(n=>{if(n.type==='heading')n.attrs.level--})});localStorage.setItem(key,JSON.stringify(all));})()`);win.webContents.reload();await delay(1100);
    const groupCount=await js(`document.querySelectorAll('.tiptap h1').length`);
    assert.ok(await js(`document.querySelector('.outline-panel').getBoundingClientRect().right <= document.querySelector('.editor-area').getBoundingClientRect().left + 1`));
    assert.equal(await js(`getComputedStyle(document.querySelector('.tiptap')).fontSize`), '17px');
    const ids = await js(`Array.from(document.querySelectorAll('.tiptap h1,.tiptap h2')).map(el=>el.dataset.headingId)`);
    assert.ok(ids.every(Boolean)); assert.equal(new Set(ids).size, ids.length);
    await fs.writeFile(path.join(output, 'editor.png'), (await win.webContents.capturePage()).toPNG());
    await js(`document.querySelector('button[aria-label="探索：霧に沈む町を折りたたむ"]').click()`);
    assert.ok(!(await js(`Array.from(document.querySelectorAll('.outline-link')).some(b=>b.textContent==='喫茶店「凪」')`)));
    await js(`document.querySelector('button[aria-label="探索：霧に沈む町を展開"]').click()`);
    await flowTab(); await delay(300);
    await js(`document.querySelector('button[aria-label="喫茶店「凪」を編集"]').click()`);
    const targetId = await js(`(()=>{const select=document.querySelector('select[aria-label="対応する目次"]');const option=Array.from(select.options).find(o=>o.textContent.trim()==='喫茶店「凪」');select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));return option.value;})()`);
    await delay(250);
    await js(`document.querySelector('[data-id="cafe"] .node-label').click()`); await delay(300);
    assert.ok(await js(`!document.querySelector('.editor-area').classList.contains('hidden')`));
    assert.equal(await js(`getSelection().anchorNode.parentElement.closest('h2')?.dataset.headingId`), targetId);
    await js(`(()=>{const el=Array.from(document.querySelectorAll('.tiptap h2')).find(el=>el.dataset.headingId===${JSON.stringify(targetId)});const range=document.createRange();range.selectNodeContents(el);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.execCommand('insertText',false,'喫茶店（改名）');})()`);
    await delay(300);
    assert.equal(await js(`Array.from(document.querySelectorAll('.tiptap h2')).find(el=>el.textContent==='喫茶店（改名）').dataset.headingId`), targetId);
    await js(`document.querySelector('button[aria-label="探索：霧に沈む町を前へ"]').click()`); await delay(200);
    await flowTab(); await delay(300);
    assert.ok(await js(`document.querySelector('[data-id="cafe"] .node-link').textContent.includes('喫茶店（改名）')`));
    await click('H1をグループ・H2をシーンに'); await delay(700);
    assert.equal(await js(`document.querySelectorAll('.scene-group').length`), groupCount);
    const count = await js(`document.querySelectorAll('.react-flow__node').length`);
    await click('H1をグループ・H2をシーンに'); await delay(700);
    assert.equal(await js(`document.querySelectorAll('.react-flow__node').length`), count);
    await fs.writeFile(path.join(output, 'grouped-flow.png'), (await win.webContents.capturePage()).toPNG());
    const groupedDoc = await js(`Object.values(JSON.parse(localStorage.getItem('trpg-canvas-documents-v1')))[0].doc`);
    await js(`document.querySelector('[data-id="cafe"] .node-label').click()`); await delay(300);
    assert.equal(await js(`getSelection().anchorNode.parentElement.closest('h2')?.dataset.headingId`), targetId);
    await delay(800); win.webContents.reload(); await delay(1100);
    await flowTab(); await delay(400);
    assert.equal(await js(`document.querySelectorAll('.scene-group').length`), groupCount);
    await js(`document.querySelector('[data-id="cafe"] .node-label').click()`); await delay(300);
    assert.equal(await js(`getSelection().anchorNode.parentElement.closest('h2')?.dataset.headingId`), targetId);
    await flowTab(); await delay(300);
    await js(`document.querySelector('button[aria-label="グループを解除"]').click()`); await delay(400);
    assert.equal(await js(`document.querySelectorAll('.scene-group').length`), 0);
    assert.equal(await js(`document.querySelectorAll('.react-flow__node').length`), count);
    await win.setSize(1000, 800); await click('シナリオ編集'); await delay(350);
    assert.ok(await js(`getComputedStyle(document.querySelector('.outline-panel')).display !== 'none'`));
    await fs.writeFile(path.join(output, 'compact-editor.png'), (await win.webContents.capturePage()).toPNG());
    const { exportHtml } = await import('../src/export.mjs');
    const htmlPath = path.join(output, 'grouped.html');
    await fs.writeFile(htmlPath, exportHtml(groupedDoc));
    await win.loadFile(htmlPath); await delay(250);
    assert.ok(await js(`document.querySelectorAll('svg a').length >= 8`));
    await fs.writeFile(path.join(output, 'grouped.pdf'), await win.webContents.printToPDF({ printBackground: true, pageSize: 'A4', margins: { top: .5, bottom: .5, left: .5, right: .5 } }));
    assert.deepEqual(errors, []);
    console.log('PASS: left outline, readable type, collapse, unique heading IDs, scene links, rename + reorder stability, nested groups, repeated grouping, persistence, ungroup, compact layout');
    win.destroy(); app.exit(0);
  } catch (error) { console.error(error); win?.destroy(); app.exit(1); }
});
