const {app,BrowserWindow}=require('electron');const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve('.test-output/images');app.setPath('userData',path.join(output,`profile-${Date.now()}`));const delay=ms=>new Promise(r=>setTimeout(r,ms));
app.whenReady().then(async()=>{try{
 await fs.mkdir(output,{recursive:true});const w=new BrowserWindow({width:1440,height:1000,show:false,webPreferences:{sandbox:true,contextIsolation:true}});const errors=[];w.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});
 const js=async code=>{try{const result=await w.webContents.executeJavaScript(code,true);await delay(100);return result;}catch(e){console.error(code);throw e;}};
 const importMd=markdown=>js(`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(markdown)}],'画像のあるシナリオ.md'));const input=document.querySelector('input[accept=".md,.markdown,.txt"]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 await w.loadFile(path.resolve('dist/index.html'));await delay(1000);w.show();w.focus();await importMd('## 地図\n\n地図を確認する。');await delay(300);
 await js(`(()=>{const p=document.querySelector('.tiptap p');const r=document.createRange();r.selectNodeContents(p);r.collapse(false);getSelection().removeAllRanges();getSelection().addRange(r);document.querySelector('.tiptap').focus();})()`);
 await js(`window.testImage=()=>new Promise(resolve=>{const c=document.createElement('canvas');c.width=640;c.height=260;const ctx=c.getContext('2d');ctx.fillStyle='#e6eedc';ctx.fillRect(0,0,640,260);ctx.fillStyle='#344a37';ctx.font='28px sans-serif';ctx.fillText('Scene Map / 画像の挿入テスト',24,60);ctx.strokeRect(40,100,150,100);ctx.strokeRect(420,100,150,100);ctx.beginPath();ctx.moveTo(190,150);ctx.lineTo(420,150);ctx.stroke();c.toBlob(blob=>resolve(new File([blob],'scene-map.png',{type:'image/png'})));});undefined`);
 await js(`(async()=>{const dt=new DataTransfer();dt.items.add(await window.testImage());const input=document.querySelector('[aria-label="挿入する画像"]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await delay(400);
 assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),1);
 await js(`(async()=>{const dt=new DataTransfer();dt.items.add(await window.testImage());document.querySelector('.tiptap').dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}));})()`);await delay(400);
 assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),2);
 await js(`(()=>{const dt=new DataTransfer();dt.items.add(new File(['<svg/>'],'bad.svg',{type:'image/svg+xml'}));const input=document.querySelector('[aria-label="挿入する画像"]');input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));})()`);await delay(250);
 assert.ok(await js(`document.querySelector('.image-error').textContent.includes('PNG')`));assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),2);await js(`document.querySelector('[aria-label="画像エラーを閉じる"]').click()`);
 await delay(850);const doc=await js(`Object.values(JSON.parse(localStorage.getItem('trpg-canvas-documents-v1'))).find(v=>v.doc.title==='画像のあるシナリオ').doc`);assert.ok(doc.markdown.includes('data:image/png;base64,'));
 w.webContents.reload();await delay(1000);await js(`Array.from(document.querySelectorAll('.document-item')).find(e=>e.textContent.includes('画像のあるシナリオ')).click()`);await delay(300);assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),2);assert.ok(await js(`[...document.querySelectorAll('.tiptap img')].every(img=>img.naturalWidth===640)`));
 await fs.writeFile(path.join(output,'editor.png'),(await w.webContents.capturePage()).toPNG());await importMd(doc.markdown);await delay(500);assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),2);await delay(850);
 const {exportHtml}=await import('../src/export.mjs');const html=path.join(output,'images.html');await fs.writeFile(html,exportHtml(doc,{columns:2}));await w.loadFile(html);assert.ok(await js(`[...document.querySelectorAll('.scenario-body img')].every(img=>img.naturalWidth===640)`));await fs.writeFile(path.join(output,'images.pdf'),await w.webContents.printToPDF({printBackground:true,pageSize:'A4'}));assert.deepEqual(errors,[]);
 console.log('PASS: local image insertion, clipboard paste, unsupported rejection, JSON reload, Markdown roundtrip, HTML and two-column PDF');app.exit(0);
}catch(e){console.error(e);app.exit(1);}});

