const {app,BrowserWindow}=require('electron');
const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve('.test-output/search');app.setPath('userData',path.join(output,`profile-${Date.now()}`));const delay=ms=>new Promise(r=>setTimeout(r,ms));
app.whenReady().then(async()=>{try{
 await fs.mkdir(output,{recursive:true});const w=new BrowserWindow({width:1440,height:1000,show:false,webPreferences:{sandbox:true,contextIsolation:true}}),errors=[];
 w.webContents.on('console-message',e=>{if(e.level==='error')errors.push(e.message);});
 const js=async code=>{const value=await w.webContents.executeJavaScript(code,true);await delay(100);return value;};
 const click=label=>js(`document.querySelector('[aria-label="${label}"]').click();undefined`);
 const button=text=>js(`[...document.querySelectorAll('.find-bar button')].find(b=>b.textContent===${JSON.stringify(text)}).click();undefined`);
 const input=(label,value)=>js(`(()=>{const el=document.querySelector('[aria-label="${label}"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,${JSON.stringify(value)});el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
 const importMd=text=>js(`(()=>{const dt=new DataTransfer();dt.items.add(new File([${JSON.stringify(text)}],'検索テスト.md'));const el=document.querySelector('input[accept=".md,.markdown,.txt"]');el.files=dt.files;el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
 const data=()=>js(`Object.values(JSON.parse(localStorage.getItem('trpg-canvas-documents-v1'))).filter(v=>v.doc.title==='検索テスト').at(-1).doc`);
 const count=()=>js(`document.querySelector('.find-count').textContent`);
 const key=async(keyCode,modifiers=[])=>{w.webContents.sendInputEvent({type:'keyDown',keyCode,modifiers});w.webContents.sendInputEvent({type:'keyUp',keyCode,modifiers});await delay(150);};
 await w.loadFile(path.resolve('dist/index.html'));await delay(1000);w.show();w.focus();
 await importMd('## 霧の町\n\n霧**の**町で出会う。<u>重要な情報</u>\n\n> [!GM]\n>\n> 霧の町の秘密\n\n- [ ] 霧の町を探索\n\nNPC npc $1 [a]');await delay(500);
 assert.equal(await js(`document.querySelector('.tiptap u').textContent`),'重要な情報');
 await key('f',['control']);assert.ok(await js(`!!document.querySelector('.find-bar')`));
 await input('検索する文字','霧の町');assert.equal(await count(),'1 / 4 件');
 await click('次の検索結果');assert.equal(await count(),'2 / 4 件');await click('前の検索結果');assert.equal(await count(),'1 / 4 件');
 await input('置換後の文字','雨の街');await button('1件置換');assert.equal(await count(),'1 / 3 件');assert.equal(await js(`document.querySelector('.tiptap h2').textContent`),'雨の街');
 await button('すべて置換');assert.equal(await count(),'見つかりません');
 await click('元に戻す（Ctrl+Z）');assert.equal(await count(),'1 / 3 件');assert.equal(await js(`document.querySelector('.tiptap h2').textContent`),'雨の街');
 await input('検索する文字','NPC');assert.equal(await count(),'1 / 2 件');await js(`document.querySelector('.find-bar input[type=checkbox]').click();undefined`);assert.equal(await count(),'1 / 1 件');
 await input('検索する文字','$1');assert.equal(await count(),'1 / 1 件');await input('置換後の文字','<img>');await button('すべて置換');assert.equal(await js(`document.querySelectorAll('.tiptap img').length`),0);assert.ok(await js(`document.querySelector('.tiptap').textContent.includes('<img>')`));
 await input('検索する文字','[a]');await input('置換後の文字','');await button('1件置換');assert.equal(await count(),'見つかりません');
 await input('検索する文字','NPC');await input('置換後の文字','NPC');await button('すべて置換');assert.equal(await count(),'1 / 1 件');
 await fs.writeFile(path.join(output,'editor.png'),(await w.webContents.capturePage()).toPNG());
 await key('Escape');assert.equal(await js(`document.querySelectorAll('.search-match').length`),0);
 await js(`(()=>{const p=[...document.querySelectorAll('.tiptap>p')].at(-1),r=document.createRange();r.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(r);document.querySelector('.tiptap').focus();})()`);
 await click('下線（Ctrl+U）');assert.ok(await js(`document.querySelector('.tiptap>p:last-child u')?.textContent.includes('NPC')`));
 await delay(850);let doc=await data();assert.ok(doc.markdown.includes('<u>'));assert.ok(!doc.markdown.includes('search-match'));
 await importMd(doc.markdown);await delay(500);assert.equal(await js(`document.querySelectorAll('.tiptap u').length`),2);
 const {markdown,exportHtml}=await import('../src/export.mjs');assert.ok(markdown.render('<u onclick="bad()">unsafe</u>').includes('&lt;u'));assert.ok(markdown.render('`<u>code</u>`').includes('&lt;u&gt;code'));assert.ok(markdown.render('<u>**bold**</u>').includes('<u><strong>bold</strong></u>'));
 const file=path.join(output,'underline.html');await fs.writeFile(file,exportHtml(doc));await w.loadFile(file);assert.equal(await js(`document.querySelectorAll('.scenario-body u').length`),2);assert.equal(await js(`getComputedStyle(document.querySelector('.scenario-body u')).textDecorationLine`),'underline');
 assert.deepEqual(errors,[]);console.log('PASS: underline roundtrip/export, literal search across marks and blocks, navigation, case, replacement/empty/same value, atomic undo, keyboard and highlight cleanup');app.exit(0);
}catch(e){console.error(e);app.exit(1);}});
