// Runs the real production renderer in Electron, with isolated browser storage.
const { app, BrowserWindow, clipboard } = require('electron');
const fs = require('node:fs/promises');
const path = require('node:path');
const assert = require('node:assert/strict');
const output = path.resolve(__dirname, '../.test-output');
app.setPath('userData', path.join(output, 'electron-profile'));
app.commandLine.appendSwitch('disable-gpu');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
app.whenReady().then(async () => {
  let win;
  try {
    await fs.mkdir(output, { recursive: true });
    win = new BrowserWindow({ width: 1440, height: 1000, show: false, webPreferences: { sandbox: true, contextIsolation: true, nodeIntegration: false } });
    const errors = [];
    win.webContents.on('console-message', (event) => { if (event.level === 'error') { errors.push(event.message); console.error('RENDERER:', event.message); } });
    await win.loadFile(path.resolve(__dirname, '../dist/index.html'));
    const js = async code => { try { return await win.webContents.executeJavaScript(code, true); } catch (e) { console.error('SCRIPT:', code); throw e; } };
    const click = text => js(`Array.from(document.querySelectorAll('button')).find(b=>b.textContent.trim()===${JSON.stringify(text)})?.click()`);
    await delay(1300);
    await js('localStorage.clear()'); await win.webContents.reload(); await delay(1300);
    assert.ok(await js('!!document.querySelector(".tiptap h2")'));
    await fs.writeFile(path.join(output, 'editor.png'), (await win.webContents.capturePage()).toPNG());
    const before = await js('document.querySelector(".tiptap h2").textContent');
    await js(`document.querySelector('button[aria-label="シナリオ概要を後へ"]').click()`);
    await delay(250);
    assert.notEqual(await js('document.querySelector(".tiptap h2").textContent'), before);
    await js(`document.querySelector('button[aria-label="元に戻す（Ctrl+Z）"]').click()`);
    await delay(200);
    assert.equal(await js('document.querySelector(".tiptap h2").textContent'), before);
    await js(`(()=>{const el=document.querySelector('.tiptap');el.focus();const range=document.createRange();range.selectNodeContents(el);range.collapse(false);const selection=getSelection();selection.removeAllRanges();selection.addRange(range);document.execCommand('insertText',false,'検証用の追記');})()`);
    await delay(1000);
    await win.webContents.reload(); await delay(800);
    assert.ok(await js('document.querySelector(".tiptap").innerText.includes("検証用の追記")'));
    await js(`(()=>{const key='trpg-canvas-documents-v1';const data=JSON.parse(localStorage.getItem(key));const item=Object.values(data)[0];item.doc.markdown+='\\n\\n外部端末の編集';delete item.doc.content;item.revision='external-revision';localStorage.setItem(key,JSON.stringify(data));document.querySelector('button[aria-label="再読込"]').click();})()`);
    await delay(700);
    assert.ok(await js('document.querySelector(".tiptap").innerText.includes("外部端末の編集")'));
    await js(`Array.from(document.querySelectorAll('.view-tabs button')).find(b=>b.textContent.includes('フローチャート')).click()`); await delay(500);
    assert.equal(await js('document.querySelectorAll(".scene-node").length'), 6);
    await click('シーン'); await delay(250);
    assert.equal(await js('document.querySelectorAll(".scene-node").length'), 7);
    await js(`(()=>{const el=document.querySelector('.flow-inspector input');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(el,'検証シーン');el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
    await delay(800);
    assert.ok(await js('document.querySelector(".flow-canvas").innerText.includes("検証シーン")'));
    await fs.writeFile(path.join(output, 'flow.png'), (await win.webContents.capturePage()).toPNG());
    await click('書き出す'); await delay(200);
    assert.ok(await js('document.querySelector("[role=dialog]").innerText.includes("コピーボタン")'));
    await fs.writeFile(path.join(output, 'export-dialog.png'), (await win.webContents.capturePage()).toPNG());
    const { sampleDocument } = await import('../src/model.mjs');
    const { exportHtml } = await import('../src/export.mjs');
    const sample = sampleDocument();
    const html = exportHtml(sample);
    const htmlPath = path.join(output, 'sample.html');
    await fs.writeFile(htmlPath, html);
    await win.loadFile(htmlPath); win.show(); win.focus(); await delay(500);
    await js('document.querySelector(".copy-button").click()'); await delay(300);
    assert.ok(clipboard.readText().includes('あなたがこれを読んでいるなら'), await js('document.querySelector(".copy-button").textContent'));
    console.log('PASS: HTML clipboard');
    await fs.writeFile(path.join(output, 'html.png'), (await win.webContents.capturePage()).toPNG());
    console.log('Printing PDF');
    await fs.writeFile(path.join(output, 'sample.pdf'), await win.webContents.printToPDF({ printBackground: true, pageSize: 'A4', margins: { top: .5, bottom: .5, left: .5, right: .5 } }));
    assert.deepEqual(errors, []);
    console.log('PASS: production renderer, section reorder + undo, editing + persistence, flow add + rename, export dialog, local HTML clipboard, PDF generation');
    win.destroy(); app.exit(0);
  } catch (error) { console.error(error); win?.destroy(); app.exit(1); }
});
