import React, { lazy, Suspense, useMemo, useState } from 'react';
import { ThemePicker, FontSizeControl } from './Appearance.jsx';
import { exportHtml } from './export.mjs';
const PdfPreview = lazy(() => import('./PdfPreview.jsx'));
export default function ExportDialog({ doc, design, onDesign, appearance, busy, onExport }) {
  const [format, setFormat] = useState('html'), [copyButtons, setCopyButtons] = useState(true), [includeFlow, setIncludeFlow] = useState(true);
  const options = { ...design, copyButtons: format === 'html' && copyButtons, includeFlow };
  const html = useMemo(() => exportHtml(doc, { ...design, copyButtons: format === 'html' && copyButtons, includeFlow, interactive: false, printPreview: format === 'pdf' && !window.canvas }), [doc, design.theme, design.fontSize, format, copyButtons, includeFlow]);
  return <div className="export-layout"><div className="export-settings"><div className="format-options">{[['html', 'HTML'], ['pdf', 'PDF'], ['md', 'Markdown']].map(([id, label]) => <button key={id} className={format === id ? 'chosen' : ''} aria-pressed={format === id} onClick={() => setFormat(id)}>{label}</button>)}</div>{format !== 'md' ? <><ThemePicker value={design.theme} onChange={theme => onDesign({ ...design, theme })} label="書き出しテーマ"/><FontSizeControl value={design.fontSize} onChange={fontSize => onDesign({ ...design, fontSize })} label="書き出しの文字サイズ"/><button className="secondary-button" onClick={() => onDesign({ theme: appearance.theme, fontSize: appearance.fontSize })}>画面と同じ設定</button>{format === 'html' && <label className="checkbox-line"><input type="checkbox" checked={copyButtons} onChange={e => setCopyButtons(e.target.checked)}/>コピーボタンを付ける</label>}<label className="checkbox-line"><input type="checkbox" checked={includeFlow} onChange={e => setIncludeFlow(e.target.checked)}/>フローチャートを含める</label></> : <p className="hint-box">Markdownは本文のみのテキスト形式です。テーマ・文字サイズ・フローチャートは含まれません。</p>}<p className="export-note">GMメモも含まれます。配布前に内容を確認してください。</p><button className="primary-button full-width" disabled={busy} onClick={() => onExport(format, options)}>{busy ? '書き出し中…' : `${format.toUpperCase()}を書き出す`}</button></div><section className="export-preview" aria-label="書き出しプレビュー"><div className="preview-heading">プレビュー <small>{format === 'pdf' && window.canvas ? 'A4・実際の改ページを表示' : format.toUpperCase()}</small></div>{format === 'md' ? <pre className="markdown-preview">{doc.markdown}</pre> : format === 'pdf' && window.canvas ? <Suspense fallback={<p>PDFプレビューを準備中…</p>}><PdfPreview html={html}/></Suspense> : <>{format === 'pdf' && <p className="preview-notice">改ページを含むPDFプレビューはデスクトップ版で利用できます。</p>}<iframe title="書き出しの仕上がり" sandbox="allow-same-origin" srcDoc={html}/></>}</section></div>;
}
