import MarkdownIt from 'markdown-it';
export const markdown = new MarkdownIt({ html: false, linkify: true, typographer: false });
export const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function flowSvg(flow) {
  if (!flow.nodes.length) return '';
  const nodes = flow.nodes, map = new Map(nodes.map(n => [n.id, n]));
  const minX = Math.min(...nodes.map(n => n.position.x)) - 30, minY = Math.min(...nodes.map(n => n.position.y)) - 30;
  const width = Math.max(...nodes.map(n => n.position.x + 230)) - minX, height = Math.max(...nodes.map(n => n.position.y + 110)) - minY;
  const paths = flow.edges.map(edge => {
    const a = map.get(edge.source), b = map.get(edge.target); if (!a || !b) return '';
    const x1 = a.position.x + 100, y1 = a.position.y + 70, x2 = b.position.x + 100, y2 = b.position.y;
    return `<path d="M ${x1} ${y1} C ${x1} ${(y1 + y2) / 2}, ${x2} ${(y1 + y2) / 2}, ${x2} ${y2}" fill="none" stroke="#789088" stroke-width="2" marker-end="url(#arrow)"/><text x="${(x1 + x2) / 2 + 9}" y="${(y1 + y2) / 2}" font-size="12" fill="#52665e">${escapeHtml(edge.label || '')}</text>`;
  }).join('');
  const boxes = nodes.map(n => {
    const color = n.data.kind === 'branch' ? '#f6ead2' : n.data.kind === 'ending' ? '#e9e5f1' : '#e6efea';
    const lines = Array.from(String(n.data.label)).reduce((arr, ch, i) => { if (i % 13 === 0) arr.push(''); arr[arr.length - 1] += ch; return arr; }, []);
    return `<g transform="translate(${n.position.x},${n.position.y})"><rect width="200" height="70" rx="10" fill="${color}" stroke="#bccbc2"/><text x="100" y="${lines.length > 1 ? 28 : 40}" text-anchor="middle" font-size="13" fill="#273d34">${lines.slice(0, 3).map((s, i) => `<tspan x="100" dy="${i ? 17 : 0}">${escapeHtml(s)}</tspan>`).join('')}</text></g>`;
  }).join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" role="img" aria-label="シナリオのフローチャート" viewBox="${minX} ${minY} ${width} ${height}"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#789088"/></marker></defs>${paths}${boxes}</svg>`;
}
export function exportHtml(doc, { copyButtons = true, includeFlow = true } = {}) {
  let html = markdown.render(doc.markdown), index = 0;
  const toc = [];
  html = html.replace(/<h([1-6])>([\s\S]*?)<\/h\1>/g, (_, level, title) => { const id = `section-${index++}`; toc.push(`<a href="#${id}" class="level-${level}">${title}</a>`); return `<h${level} id="${id}">${title}</h${level}>`; });
  if (copyButtons) html = html.replace(/<(blockquote|pre)>([\s\S]*?)<\/\1>/g, (_, tag, content) => `<div class="copy-block"><button type="button" class="copy-button">コピー</button><${tag}>${content}</${tag}></div>`);
  const script = copyButtons ? `<script>document.querySelectorAll('.copy-button').forEach(button=>button.addEventListener('click',async()=>{const text=button.nextElementSibling.innerText;try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw new Error('copy');}button.textContent='コピーしました';}catch{button.textContent='選択してコピーしてください';const range=document.createRange();range.selectNodeContents(button.nextElementSibling);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);}setTimeout(()=>button.textContent='コピー',2000);}));</script>` : '';
  return `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:"><title>${escapeHtml(doc.title)}</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f7f6f1;color:#293b34;font:15px/1.95 'Yu Gothic','Meiryo',sans-serif}main{max-width:850px;margin:48px auto;padding:55px 65px;background:white;border:1px solid #e3e6df;border-radius:12px}header{border-bottom:1px solid #dce3dc;padding-bottom:28px;margin-bottom:30px}header small{letter-spacing:3px;color:#61806f}h1{font-size:32px;line-height:1.5}h2{margin-top:42px;border-bottom:1px solid #e3e8e2;padding-bottom:10px;font-size:23px}h3{margin-top:28px;font-size:18px}nav{background:#f3f6f2;padding:20px 25px;border-radius:8px}nav a{display:block;color:#436654;text-decoration:none}nav .level-3{padding-left:18px;font-size:13px}blockquote{margin:20px 0;padding:18px 24px;border-left:3px solid #69937e;background:#f0f5ef}blockquote p:first-child{margin-top:0}blockquote p:last-child{margin-bottom:0}pre{padding:22px;background:#edf1ec;white-space:pre-wrap;overflow-wrap:anywhere}code{font-family:Consolas,monospace;background:#eef1eb;padding:2px 4px}.copy-block{position:relative}.copy-block blockquote,.copy-block pre{padding-top:42px}.copy-button{position:absolute;right:10px;top:10px;background:white;border:1px solid #ced9cd;border-radius:5px;color:#52715c;padding:5px 10px;cursor:pointer}svg{width:100%;height:auto;max-height:900px}a{color:#426e58}hr{border:0;border-top:1px solid #ddd}footer{margin-top:40px;color:#849184;font-size:11px;text-align:center}@media(max-width:650px){main{margin:0;padding:28px 22px;border:0}}@media print{body{background:white;font-size:10pt}main{margin:0;padding:0;border:0;max-width:none}nav,.copy-button{display:none}h1,h2,h3{break-after:avoid}blockquote,pre,svg{break-inside:avoid}.copy-block blockquote,.copy-block pre{padding-top:18px}a{color:inherit;text-decoration:none}.flow-section{break-before:page}}
  </style></head><body><main><header><small>TRPG CANVAS / SCENARIO</small><h1>${escapeHtml(doc.title)}</h1><p>${escapeHtml(doc.subtitle || '')}</p></header><nav aria-label="目次">${toc.join('')}</nav>${html}${includeFlow && doc.flow.nodes.length ? `<section class="flow-section"><h2>シナリオフロー</h2>${flowSvg(doc.flow)}</section>` : ''}<footer>Created with TRPG Canvas</footer></main>${script}</body></html>`;
}
