import { readPreference } from './themes.mjs';
import React, { lazy, Suspense, useMemo, useState, useEffect } from 'react';
import { ThemePicker, FontSizeControl } from './Appearance.jsx';
import { exportHtml } from './export.mjs';
const PdfPreview = lazy(() => import('./PdfPreview.jsx'));
export default function ExportDialog({ doc, design, onDesign, appearance, busy, onExport }) {
  const [format, setFormat] = useState('html'), [copyButtons, setCopyButtons] = useState(true), [includeFlow, setIncludeFlow] = useState(true);
  const [columns, setColumns] = useState(() => readPreference('trpg-pdf-columns', 1) === 2 ? 2 : 1);
  const [pageSize, setPageSize] = useState(() => ['A4', 'A5', 'B5', 'Letter'].includes(readPreference('trpg-pdf-page-size', 'A4')) ? readPreference('trpg-pdf-page-size', 'A4') : 'A4');
  useEffect(() => { try { localStorage.setItem('trpg-pdf-columns', JSON.stringify(columns)); } catch {} }, [columns]);
  useEffect(() => { try { localStorage.setItem('trpg-pdf-page-size', JSON.stringify(pageSize)); } catch {} }, [pageSize]);
  const options = { ...design, columns: format === 'pdf' ? columns : 1, pdfPageSize: pageSize, copyButtons: format === 'html' && copyButtons, includeFlow };
  const html = useMemo(() => exportHtml(doc, { ...design, columns: format === 'pdf' ? columns : 1, pdfPageSize: pageSize, copyButtons: format === 'html' && copyButtons, includeFlow, interactive: false, printPreview: format === 'pdf' && !window.canvas }), [doc, design.theme, design.fontSize, format, copyButtons, includeFlow, columns, pageSize]);
  return <div className="export-layout"><div className="export-settings"><div className="format-options">{[['html', 'HTML'], ['pdf', 'PDF'], ['md', 'Markdown']].map(([id, label]) => <button key={id} className={format === id ? 'chosen' : ''} aria-pressed={format === id} onClick={() => setFormat(id)}>{label}</button>)}</div>{format !== 'md' ? <><ThemePicker value={design.theme} onChange={theme => onDesign({ ...design, theme })} label="書き出しテーマ"/><FontSizeControl value={design.fontSize} onChange={fontSize => onDesign({ ...design, fontSize })} label="書き出しの文字サイズ" min={7}/><button className="secondary-button" onClick={() => onDesign({ theme: appearance.theme, fontSize: appearance.fontSize })}>画面と同じ設定</button>{format === 'pdf' && <><fieldset className="pdf-page-sizes"><legend>用紙サイズ</legend><div>{[['A4', 'A4'], ['A5', 'A5'], ['B5', 'B5（JIS）'], ['Letter', 'レター']].map(([value, label]) => <button key={value} aria-pressed={pageSize === value} onClick={() => setPageSize(value)}>{label}</button>)}</div></fieldset><fieldset className="pdf-columns"><legend>本文の段組み</legend><div>{[1, 2].map(value => <button key={value} aria-pressed={columns === value} onClick={() => setColumns(value)}>{value}段組み</button>)}</div><p>タイトルとフローチャートはページ幅いっぱいに表示します。</p></fieldset></>}{format === 'html' && <label className="checkbox-line"><input type="checkbox" checked={copyButtons} onChange={e => setCopyButtons(e.target.checked)}/>コピーボタンを付ける</label>}<label className="checkbox-line"><input type="checkbox" checked={includeFlow} onChange={e => setIncludeFlow(e.target.checked)}/>フローチャートを含める</label></> : <p className="hint-box">Markdownは本文のみのテキスト形式です。テーマ・文字サイズ・フローチャートは含まれません。</p>}<p className="export-note">GMメモも含まれます。配布前に内容を確認してください。</p><button className="primary-button full-width" disabled={busy} onClick={() => onExport(format, options)}>{busy ? '書き出し中…' : `${format.toUpperCase()}を書き出す`}</button></div><section className="export-preview" aria-label="書き出しプレビュー"><div className="preview-heading">プレビュー <small>{format === 'pdf' && window.canvas ? `${pageSize}・実際の改ページを表示` : format.toUpperCase()}</small></div>{format === 'md' ? <pre className="markdown-preview">{doc.markdown}</pre> : format === 'pdf' && window.canvas ? <Suspense fallback={<p>PDFプレビューを準備中…</p>}><PdfPreview html={html} pageSize={pageSize}/></Suspense> : <>{format === 'pdf' && <p className="preview-notice">改ページを含むPDFプレビューはデスクトップ版で利用できます。</p>}<iframe title="書き出しの仕上がり" sandbox="allow-same-origin" srcDoc={html}/></>}</section></div>;
}
