import { getTheme, normalizeDesign } from './themes.mjs';
export function exportStyle(options) {
  const { theme, fontSize } = normalizeDesign(options), t = getTheme(theme), c = t.colors;
  const headingStyle = '.scenario-body :is(h1,h2,h3,h4,h5,h6){margin:2em 0 .55em;padding-bottom:0;line-height:1.5;break-after:avoid;break-inside:avoid}.scenario-body h2{padding-bottom:.3em}.scenario-body h4{font-size:1.1em}.scenario-body h5{font-size:1em}.scenario-body h6{font-size:.95em}.scenario-body .chapter-heading{font-size:2.2em;text-align:center;margin:2.5em 0 .7em;letter-spacing:.08em;border:0}nav .level-0{font-weight:bold;margin-top:.5em}';
  const navigationStyle = `.scenario-body h1{color:${c.heading}}.scenario-body :is(h2,h3,h4,h5,h6){color:${c.subheading}}.scenario-body .chapter-heading{color:${c.chapter}}.blank-line{min-height:1.95em}.export-toc{margin:26px 0 42px;padding:26px 30px;border:1px solid ${c.border};border-radius:12px;background:${c.paper};box-shadow:0 4px 18px #00000005}.toc-heading{display:flex;align-items:center;gap:16px;padding-bottom:16px;margin-bottom:10px;border-bottom:1px solid ${c.border}}.toc-heading>span{font:10px sans-serif;letter-spacing:3px;color:${c.accent}}.toc-heading>strong{font-size:1em;font-weight:500;color:${c.heading}}.toc-links{counter-reset:toc}.toc-links a{display:flex;align-items:baseline;gap:12px;padding:8px 4px;color:${c.text};line-height:1.6;border-radius:4px}.toc-links a:hover{background:${c.soft}}.toc-links a:before{counter-increment:toc;content:counter(toc,decimal-leading-zero);font:11px sans-serif;color:${c.muted};min-width:20px}.toc-links .level-0{color:${c.chapter};font-weight:600;margin-top:12px;border-bottom:1px solid ${c.border}}.toc-links .level-1{color:${c.heading};font-weight:600}.toc-links .level-2{padding-left:24px;font-size:.92em}.toc-links a span{flex:1}.toc-links a:after{content:'↗';color:${c.muted};font-size:.8em}@media print{.export-toc{display:none}}`;
  const columns = options.columns === 2 ? '.scenario-body{column-count:2;column-gap:8mm;column-fill:balance}.scenario-body h1,.scenario-body h2,.scenario-body h3,.scenario-body h4{break-after:avoid}.scenario-body p{orphans:2;widows:2}.scenario-body blockquote,.scenario-body pre,.scenario-body .gm-note,.scenario-body .copy-block{break-inside:avoid}.scenario-body blockquote,.scenario-body pre,.scenario-body .gm-note{padding-left:14px;padding-right:14px}' : '';
  const pagination = '.scenario-body > h1 ~ h1{break-before:' + (options.columns === 2 ? 'column' : 'page') + '}.scenario-body .gm-note,.scenario-body blockquote,.scenario-body .copy-block{break-inside:avoid}';
  return `${headingStyle}${navigationStyle}ul[data-type="taskList"]{list-style:none;padding-left:0}li[data-type="taskItem"]{display:flex;align-items:flex-start;gap:8px}li[data-type="taskItem"]>label{flex:none;display:flex;align-items:center;min-height:1.95em}li[data-type="taskItem"]>label input{width:14px;height:14px;accent-color:${c.accent};margin:0}li[data-type="taskItem"]>div{flex:1;min-width:0}li[data-type="taskItem"] ul{margin:0 0 0 14px}.scenario-body img{display:block;max-width:100%;height:auto;max-height:220mm;object-fit:contain;margin:12px 0;break-inside:avoid}.scenario-body p{margin:0}.scenario-body{font-synthesis:style}body{background:${c.bg};color:${c.text};font-size:${fontSize}px}main{background:${c.paper};border-color:${c.border}}h1{font-size:2em}h2{font-size:1.5em}h3{font-size:1.2em}h1,h2,h3{font-family:${t.serif ? "'Yu Mincho',serif" : 'sans-serif'}}header,h2,hr{border-color:${c.border}}header small,footer{color:${c.muted}}nav,pre,code{background:${c.soft}}nav a,a{color:${c.accent}}nav .level-3{font-size:.9em}blockquote{background:${c.quote};border-color:${c.accent}}.gm-note{background-color:${c.note};color:${c.text};border-color:${c.border}}.gm-note:before{color:${c.muted}}.copy-button{background:${c.paper};color:${c.accent};border-color:${c.border}}main{overflow-wrap:anywhere}*{print-color-adjust:exact;-webkit-print-color-adjust:exact}@media print{body{background:${c.paper};font-size:${fontSize}px}main{border-radius:0}${columns}${pagination}}${options.printPreview ? columns + pagination : ''}${options.printPreview ? 'nav,.copy-button{display:none}main{margin:0;border:0;border-radius:0}.copy-block blockquote,.copy-block pre{padding-top:18px}' : ''}`;
}
