import React, { useCallback, useState } from 'react';
import { ReactFlow, Background, Controls, MiniMap, Handle, Position, addEdge, applyNodeChanges, applyEdgeChanges, MarkerType } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { Plus, GitBranch, Flag, Trash2, X } from 'lucide-react';
import { uid } from './model.mjs';
const kindNames = { scene: 'シーン', branch: '分岐', ending: 'エンディング' };
function SceneNode({ data, selected }) {
  return <div className={`scene-node ${data.kind || 'scene'} ${selected ? 'selected' : ''}`}><Handle type="target" position={Position.Top}/><small>{kindNames[data.kind] || 'シーン'}</small><div>{data.label}</div><Handle type="source" position={Position.Bottom}/></div>;
}
const nodeTypes = { scene: SceneNode };
export default function Flow({ flow, onChange }) {
  const [selected, setSelected] = useState(null);
  const nodes = flow.nodes.map(n => ({ ...n, type: 'scene' }));
  const edges = flow.edges.map(e => ({ ...e, markerEnd: { type: MarkerType.ArrowClosed }, style: { stroke: '#799185', strokeWidth: 1.6 } }));
  const item = selected?.type === 'node' ? nodes.find(n => n.id === selected.id) : edges.find(e => e.id === selected?.id);
  const change = useCallback(patch => onChange({ ...flow, ...patch }), [flow, onChange]);
  function add(kind) { const id = uid(); change({ nodes: [...flow.nodes, { id, type: 'scene', position: { x: 170 + (nodes.length % 3) * 230, y: 80 + Math.floor(nodes.length / 3) * 150 }, data: { label: kind === 'branch' ? '新しい分岐' : kind === 'ending' ? '新しい結末' : '新しいシーン', kind } }] }); setSelected({ type: 'node', id }); }
  return <div className="flow-view"><div className="flow-toolbar"><div><strong>物語のつながり</strong><span>点をつないで、分岐をつくる</span></div><button onClick={() => add('scene')}><Plus size={15}/>シーン</button><button onClick={() => add('branch')}><GitBranch size={15}/>分岐</button><button onClick={() => add('ending')}><Flag size={15}/>結末</button></div><div className="flow-canvas"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={changes => change({ nodes: applyNodeChanges(changes, flow.nodes) })} onEdgesChange={changes => change({ edges: applyEdgeChanges(changes, flow.edges) })} onConnect={connection => change({ edges: addEdge({ ...connection, id: uid() }, flow.edges) })} onNodeClick={(_, node) => setSelected({ type: 'node', id: node.id })} onEdgeClick={(_, edge) => setSelected({ type: 'edge', id: edge.id })} onPaneClick={() => setSelected(null)} fitView fitViewOptions={{ padding: 0.2 }} minZoom={0.2} maxZoom={2} deleteKeyCode={null}><Background color="#cbd4c9" gap={22} size={1}/><Controls showInteractive={false}/><MiniMap nodeColor={n => n.data.kind === 'branch' ? '#d9c18f' : '#a6c2b0'} maskColor="rgba(244,246,240,.65)"/></ReactFlow>{!nodes.length && <div className="flow-empty"><GitBranch size={36}/><h3>物語の道筋を描こう</h3><p>「＋ シーン」から最初の場面を追加してください。</p></div>}{item && <div className="flow-inspector"><div className="inspector-heading"><strong>{selected.type === 'node' ? 'シーンの編集' : 'つながりの編集'}</strong><button className="icon-button" aria-label="編集を閉じる" onClick={() => setSelected(null)}><X size={16}/></button></div><label>{selected.type === 'node' ? 'シーン名' : '条件・ラベル'}<input maxLength={100} value={selected.type === 'node' ? item.data.label : item.label || ''} onChange={e => selected.type === 'node' ? change({ nodes: flow.nodes.map(n => n.id === item.id ? { ...n, data: { ...n.data, label: e.target.value } } : n) }) : change({ edges: flow.edges.map(edge => edge.id === item.id ? { ...edge, label: e.target.value } : edge) })}/></label>{selected.type === 'node' && <label>種類<select value={item.data.kind || 'scene'} onChange={e => change({ nodes: flow.nodes.map(n => n.id === item.id ? { ...n, data: { ...n.data, kind: e.target.value } } : n) })}>{Object.entries(kindNames).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></label>}<button className="danger-link" onClick={() => { if (selected.type === 'node') change({ nodes: flow.nodes.filter(n => n.id !== item.id), edges: flow.edges.filter(e => e.source !== item.id && e.target !== item.id) }); else change({ edges: flow.edges.filter(e => e.id !== item.id) }); setSelected(null); }}><Trash2 size={14}/>この{selected.type === 'node' ? 'シーン' : 'つながり'}を削除</button></div>}<div className="flow-tip">ドラッグで移動 · 下の点から上の点へつないで接続 · クリックで編集</div></div></div>;
}
